# Generated by Django 4.1 on 2022-08-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myGrimoire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TarotCard',
        ),
    ]
