# Generated by Django 4.1 on 2022-08-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myGrimoire', '0003_tarotcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
